### ISSUE TITLE
请问大佬是用什么哪个linux系统的？

### ISSUE THREAD

**Issue by encryption-name** [pengshulin/copybook_generator#2]
在windows上折腾了好几个小时。。。

**Comment by pengshulin** [comment]
XUBUNTU 16.04 LTS, 虚拟机运行WIN7系统打包成SETUP.EXE

**Comment by encryption-name** [comment]
哦哦 请问环境还有吗？ 我想看看cairosvg包是什么版本的？我安装的一直报错
   raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2

**Comment by encryption-name** [comment]
哦哦 请问环境还有吗？ 我想问问python是什么版本的？打包成exe后，打开exe就报错。这是在CopybookGeneratorApp.log中的
Traceback (most recent call last):
  File "CopybookGeneratorApp.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "cairosvg\__init__.pyc", line 38, in <module>
  File "pathlib.pyc", line 1255, in read_text
  File "pathlib.pyc", line 1241, in open
  File "pathlib.pyc", line 1109, in _opener
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\[download]\\copybook_generator-master\\copybook_generator-master\\dist\\VERSION'

**Comment by pengshulin** [comment]
当时版本比较老，还是Python2.7，后来升级到Python3之后就没有维护过。
刚才在UBUNTU下用Python2调用了一下，还能工作。
